# Generated by Django 3.1.2 on 2020-11-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201115_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='update',
            new_name='updated',
        ),
    ]
