# Generated by Django 3.1.2 on 2020-11-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
