# Generated by Django 3.1.2 on 2020-11-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/blog', verbose_name='Изображение'),
        ),
    ]
