# Generated by Django 3.1.2 on 2020-11-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='vid_link',
            field=models.CharField(default='', max_length=120, verbose_name='Ссылка на видос'),
            preserve_default=False,
        ),
    ]
