# Generated by Django 3.1.2 on 2020-11-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201126_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='vid_link',
            field=models.CharField(max_length=120, null=True, verbose_name='Ссылка на видос'),
        ),
    ]
